version: "3.8"

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-demo}
    ports:
      - 5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
      - ./resources/classic-rock-raw-data.csv:/tmp/classic-rock-raw-data.csv:ro
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-demo@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 30080:80
    depends_on:
      - postgres
